Repository AY2425S1-CS2103T-T10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#175 Remove unused fields
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Role.java
Labels: priority.Low, severity.VeryLow, alpha-bug

#187 Fix duplicate person
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/commands/PotentialCommand.java
Labels: type.Bug, priority.Medium, alpha-bug

#181 Update index message
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DemoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PromoteCommand.java
Labels: type.Bug, severity.Medium, alpha-bug

#176 Update UG for FindCommand
  docs/UserGuide.md
  docs/images/findJohnResult.png
Labels: type.Task, priority.High, severity.High

#189 Update role department
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Role.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
Labels: type.Bug, severity.Low, alpha-bug

#184 Fix issues with CED
  src/main/java/seedu/address/model/person/ContractEndDate.java
  src/test/java/seedu/address/model/person/ContractEndDateTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#179 Update test cases
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#192 Change error message of ced for promote command
  src/main/java/seedu/address/logic/parser/PromoteCommandParser.java
  src/test/java/seedu/address/logic/parser/PromoteCommandParserTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#190 Simplify UML diagram
  docs/diagrams/DemoteSequenceDiagram.puml
Labels: type.Bug, priority.High, severity.High, alpha-bug

#195 Standardise the format of order parameter
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#197 Make order parameter optional
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Bug, severity.Low, alpha-bug

#196 Update UG for sort
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortDateCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: type.Task, priority.High

#202 Update message of commands
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DemoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/FindPotentialCommand.java
  src/main/java/seedu/address/logic/commands/PromoteCommand.java
Labels: type.Bug, priority.Medium, alpha-bug

#207 Modify StaffSync Help GUI
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.Medium

#208 Add Appendix:Effort and Appendix:Planned Enhancement
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#205 Fix UG Bugfixes Part 5
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Bug, priority.High, alpha-bug

#212 Modify DG Acknowledgements, and Delete related; Remove Implementation
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#210 Update FindCommand format
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Medium, alpha-bug

#203 Update image name
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Low, alpha-bug

#213 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.Medium, alpha-bug

#214 Add v1.5 changes for sort in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#215 Fix StaffSync UI Bugs Part 6
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/helpWindow.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCardEmployee.fxml
  src/main/resources/view/PersonListCardPotential.fxml
Labels: type.Bug, severity.High, alpha-bug

#217 Update FindCommand UML Diagram
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, severity.Medium, alpha-bug

#219 Improve content of UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow

#220 Fix StaffSync UI Part 7
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#221 Fix breakline missing in actual website
  docs/UserGuide.md
Labels: severity.VeryLow

#223 Change addressbook to staffSync
  docs/UserGuide.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.Medium

#224 Fix formatting issues in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Epic, priority.High, severity.VeryLow

#228 Add Glossary section to UG
  docs/UserGuide.md
Labels: priority.High, severity.High

#227 Add and update images in UG
  docs/UserGuide.md
  docs/images/v1.6images/Clear.png
  docs/images/v1.6images/Delete.png
  docs/images/v1.6images/Demote.png
  docs/images/v1.6images/Edit.png
  docs/images/v1.6images/Employee.png
  docs/images/v1.6images/Find.png
  docs/images/v1.6images/GUI.png
  docs/images/v1.6images/Help.png
  docs/images/v1.6images/List.png
  docs/images/v1.6images/Potential.png
  docs/images/v1.6images/Promote.png
  docs/images/v1.6images/Sort.png
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#233 Update UG
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.Medium

#283 Fix PE-D documentation bugs and Change language
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, priority.High, PE-D Documentation Bugs

#285 Resolve PE-D bugs on DG and Promote Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/PromoteCommandParser.java
  src/test/java/seedu/address/logic/parser/PromoteCommandParserTest.java
Labels: PE-D Functionality Bugs, PE-D Documentation Bugs

#288 Add Why StaffSync, Modify full width code, padding
  docs/UserGuide.md
Labels: priority.Medium

#286 Fix bugs related to sort
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/PersonDateComparator.java
  src/main/java/seedu/address/model/person/PersonDateReverseComparator.java
Labels: type.Bug, priority.High, PE-D Feature Flaws

#289 Update UG for 2101
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High, PE-D Documentation Bugs

#282 Update FindCommandParser to throw an error message when there are emp…
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PredicateContainer.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.High, severity.Medium, PE-D Functionality Bugs

#295 Improve language used in UG
  docs/UserGuide.md
Labels: priority.Low, severity.VeryLow

#292 Remove tags from DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Bug, priority.Medium, severity.Medium

#291 Made Person more defensive
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/ContractEndDateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#290 Update DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, PE-D Documentation Bugs

#297 Update DG
  docs/DeveloperGuide.md
  docs/images/Ui.png
Labels: type.Task, priority.Medium

#300 Fix missing use case end and full stop
  docs/DeveloperGuide.md
Labels: type.Task, type.Bug
