Repository AY2425S1-CS2103T-T10-2/tp, pull requests merged in 2024-10, with the labels that each got.

#51 Add use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#41 Modify Developer Guide for NFR
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#53 Update value proposition
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#54 Update glossary with GUI definition
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#63 add employee command
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EmployeeCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EmployeeCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#64 Remove tags from employee
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#62 Modify DG and UG for delete feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#66 Add department, role and CED to Employee
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ContractEndDate.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EmployeeCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#65 Change the help function
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#69 Update Find Command
  docs/UserGuide.md
Labels: type.Task, priority.High

#73 Add list e and list ph
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/ListPotentialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/ListEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPotentialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#77 Add test for FindCommandParser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#79 Fix parser bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, severity.Medium

#76 Modify delete command to support Potential Hire and Employee
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeletePotentialCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEmployeeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EmployeeCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#81 Improve and update help feature
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.High

#86 Change list to list all
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#87 Update add documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/commands/PotentialCommand.java
Labels: type.Story, priority.High

#90 Update Find parameters and add new test for Find
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/FindPotentialCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPotentialCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#93 Add test cases
  src/test/java/seedu/address/logic/commands/PotentialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PotentialCommandParserTest.java
  src/test/java/seedu/address/model/person/ContractEndDateTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#91 Update DeveloperGuide and UserGuide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpWindow.png
Labels: type.Task, priority.High

#95 Update help feature , UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#96 Modify UG styling
  docs/UserGuide.md
Labels: severity.VeryLow

#94 Add UG and DG for list
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task, priority.High

#98 Update user guide
  docs/UserGuide.md
  docs/images/helpWindow.png
Labels: type.Task, priority.High

#102 Add test for FindCommandParser when parsing empty keywords
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Story, priority.High

#105 Update help feature
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#108 Fix edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#110 Fix test cases
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
Labels: type.Bug, severity.Low

#113 Add demote command feature
  src/main/java/seedu/address/logic/commands/DemoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DemoteCommandParser.java
  src/test/java/seedu/address/logic/commands/DemoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DemoteCommandParserTest.java
Labels: type.Story, priority.High

#112 Modify entire GUI of StaffSync
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/DMSans/DMSans-Black.ttf
  src/main/resources/fonts/DMSans/DMSans-BlackItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-Bold.ttf
  src/main/resources/fonts/DMSans/DMSans-BoldItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-ExtraBold.ttf
  src/main/resources/fonts/DMSans/DMSans-ExtraBoldItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-ExtraLight.ttf
  src/main/resources/fonts/DMSans/DMSans-ExtraLightItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-Italic.ttf
  src/main/resources/fonts/DMSans/DMSans-Light.ttf
  src/main/resources/fonts/DMSans/DMSans-LightItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-Medium.ttf
  src/main/resources/fonts/DMSans/DMSans-MediumItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-Regular.ttf
  src/main/resources/fonts/DMSans/DMSans-SemiBold.ttf
  src/main/resources/fonts/DMSans/DMSans-SemiBoldItalic.ttf
  src/main/resources/fonts/DMSans/DMSans-Thin.ttf
  src/main/resources/fonts/DMSans/DMSans-ThinItalic.ttf
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCardEmployee.fxml
  src/main/resources/view/PersonListCardPotential.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Medium

#119 change the behaviour of list to work closer to other commands
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#122 Modify GUI files for refactoring
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCardEmployee.fxml
  src/main/resources/view/PersonListCardPotential.fxml
Labels: severity.VeryLow

#123 Create promote feature and update demote command
  src/main/java/seedu/address/logic/commands/DemoteCommand.java
  src/main/java/seedu/address/logic/commands/PromoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PromoteCommandParser.java
  src/test/java/seedu/address/logic/commands/DemoteCommandTest.java
  src/test/java/seedu/address/logic/commands/PromoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DemoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PromoteCommandParserTest.java
Labels: type.Task, priority.High

#121 Modify delete to support extra spaces bet params
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, priority.Medium

#126 Add SortNameCommand
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/PersonNameComparator.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/PotentialCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonNameComparatorTest.java
Labels: type.Task, priority.High

#124 Add extra parameters to FindCommandParser to parse
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/FindPotentialCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PredicateContainer.java
  src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPotentialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/DepartmentContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PredicateContainerTest.java
  src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#129 Add test for PredicateContainer
  src/test/java/seedu/address/model/person/PredicateContainerTest.java
Labels: type.Task, priority.High

#131 Update DG and UG for promote and demote command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#132 Add SortDateCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortDateCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/ContractEndDate.java
  src/main/java/seedu/address/model/person/PersonDateComparator.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/ContractEndDateTest.java
  src/test/java/seedu/address/model/person/PersonDateComparatorTest.java
Labels: type.Task, priority.High

#134 Update FindCommand Message Usage
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Task, priority.High

#133 Update message string of commands
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DemoteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/PromoteCommand.java
Labels: type.Enhancement, priority.Medium

#135 Add message format to commands
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/commands/PotentialCommand.java
Labels: type.Bug, priority.Medium

#137 Remove PARAMETER
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Enhancement, priority.Medium

#136 Update help 2
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeletePotentialCommand.java
Labels: type.Task, priority.Medium

#143 Update format of HelpWindow command strings and DG
  docs/DeveloperGuide.md
  docs/diagrams/DemoteSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmployeeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PotentialCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#144 Modify ModelClassDiagram and Diagram Colours
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#142 Update UG and DG for sort command and add UML diagram for list command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListSequenceDiagram.puml
Labels: type.Task, priority.High

#145 Add EditSequenceDiagram.puml
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
Labels: type.Task, priority.High

#141 Update UG, DG and FindCommand message usage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Task, priority.High

#147 User Guide GUI Overhaul
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpWindow.png
Labels: type.Task, priority.High

#152 Fix UG bugfix Part 3
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.High

#153 Fix UG Bugfixes Part 4
  docs/UserGuide.md
Labels: type.Bug, severity.Low
